// Descripciones cortas y factuales de cada título (sinopsis pública del juego).
// No describen el estado, la edición ni el idioma de la copia física: eso se
// confirma por WhatsApp con el negocio.
export const DESCRIPCIONES = {
  'juegos1-00': 'Aventura de plataformas de Kirby con hasta cuatro jugadores en cooperativo local, donde puedes convertir enemigos en aliados.',
  'juegos1-01': 'Luigi explora un hotel embrujado piso por piso, capturando fantasmas con la Succionaentes y su doble viscoso, Gluigi.',
  'juegos1-02': 'El karting definitivo de Nintendo: 48 pistas, todos los personajes de la saga y multijugador local y en línea.',
  'juegos1-03': 'Táctico por turnos con la escuadra clásica de Metal Slug, arte pixel-art y combos entre unidades.',
  'juegos1-04': 'Metroidvania de exploración en una nave gigantesca a la deriva, con combate ágil y mundo interconectado.',
  'juegos1-05': 'Un tendero de día y héroe de mazmorras de noche: saquea reliquias y ponles precio en tu propia tienda.',
  'juegos1-06': 'Metroidvania oscuro y exigente de combate cuerpo a cuerpo, con arte pintado a mano y muerte permanente.',
  'juegos1-07': 'JRPG por turnos de la saga Neptunia, con humor otaku y un elenco de diosas de las consolas.',
  'juegos1-08': 'Plataformas 2D de Mario con más de 160 niveles, hasta cuatro jugadores y los personajes de New Super Luigi U.',
  'juegos1-09': 'Acción 2D de ritmo rápido en el universo Ninja Gaiden, con combate acrobático y estética de 16 bits.',
  'juegos1-10': 'Aventura de plataformas emotiva y visualmente cuidada, con exploración tipo metroidvania y banda sonora orquestal.',
  'juegos1-11': 'Secuela de Ori con más combate, nuevas habilidades y un mundo pintado a mano aún más grande.',
  'juegos1-12': 'Plataformas en pixel-art donde un búho mudo carga a sus amigos para usar sus poderes en el combate.',
  'juegos1-13': 'RPG de Pokémon ambientado en Ciudad Luminalia, con combates en tiempo real y megaevoluciones.',
  'juegos1-14': 'Versión para Nintendo Switch 2 de Leyendas Pokémon: Z-A, con mejoras de rendimiento y resolución.',
  'juegos1-15': 'RPG de Pokémon pensado para todo público, con Eevee como compañero y captura al estilo Pokémon GO.',
  'juegos1-16': 'Remake del clásico de mazmorras donde te conviertes en Pokémon y armas tu propio equipo de rescate.',
  'juegos1-17': 'RPG de mundo abierto en la región de Paldea, con tres historias paralelas y exploración libre.',
  'juegos1-18': 'RPG de la octava generación en la región de Galar, con combates Dinamax y el Área Silvestre.',
  'juegos1-19': 'Remake de Pokémon Perla ambientado en Sinnoh, fiel al original con gráficos chibi renovados.',
  'juegos1-20': 'Pack doble con los remakes de Sinnoh: Pokémon Brilliant Diamond y Pokémon Shining Pearl.',
  'juegos1-21': 'Recorre ecosistemas fotografiando Pokémon en su hábitat natural. Relajado y ideal para toda la familia.',
  'juegos1-22': 'RPG de mundo abierto en Paldea con el legendario Miraidon y exploración cooperativa en línea.',
  'juegos1-23': 'Metroidvania de acción con Sargón, combate rápido, poderes del tiempo y una mitología persa reinterpretada.',
  'juegos1-24': 'Nueva entrega de survival horror de Capcom para Nintendo Switch 2, dentro de la saga Resident Evil.',
  'juegos1-25': 'Roguelite de plataformas donde cada heredero hereda el castillo con rasgos distintos. Muere, mejora y vuelve.',
  'juegos1-26': 'Acción y aventura basada en la serie animada de Genndy Tartakovsky, con combate a espada y viajes en el tiempo.',
  'juegos1-27': 'RPG por turnos inspirado en los clásicos de 16 bits, con arte pixel-art y ciclos de día y noche.',
  'juegos1-28': 'Metroidvania de acción del universo PAC-MAN, con exploración laberíntica y un tono más oscuro.',
  'juegos1-29': 'Shoot’em up roguelike de naves con jefes gigantes, armas aleatorias y partidas cortas e intensas.',

  'juegos2-00': 'Recopilación con Super Mario 64, Super Mario Sunshine y Super Mario Galaxy en un solo cartucho.',
  'juegos2-01': 'Plataformas 3D cooperativo para cuatro jugadores, más la campaña adicional Bowser’s Fury en mundo abierto.',
  'juegos2-02': 'Los dos Super Mario Galaxy en un solo juego: plataformas 3D en planetas con gravedad propia.',
  'juegos2-03': 'Crea, comparte y juega niveles de Mario con herramientas de diseño y un modo historia completo.',
  'juegos2-04': 'Mario recorre reinos muy distintos con Cappy, la gorra que le permite poseer enemigos y objetos.',
  'juegos2-05': 'Remake del RPG clásico de Mario con combate por turnos, ataques en equipo y humor de la saga.',
  'juegos2-06': 'Plataformas 2D con las Flores Prodigio, que transforman los niveles por completo. Hasta cuatro jugadores.',
  'juegos2-07': 'El crossover de peleas más grande de Nintendo: más de 80 luchadores y multijugador local y en línea.',
  'juegos2-08': 'RPG de mundo abierto en Tamriel con las expansiones incluidas y controles de movimiento en Switch.',
  'juegos2-09': 'Metroidvania soulslike en pixel-art con ambientación gótica, combate exigente y armas variadas.',
  'juegos2-10': 'Aventura de mundo abierto en Hyrule con libertad total de exploración, física y supervivencia.',
  'juegos2-11': 'Remake del clásico de Game Boy con estética de diorama, mazmorras clásicas y un editor propio.',
  'juegos2-12': 'Plataformas de acción que salta de los 8 a los 16 bits, con humor y un giro a metroidvania.',
  'juegos2-13': 'JRPG masivo sobre dos titanes, con combate en tiempo real y un mundo abierto enorme.',
  'juegos2-14': 'Tercera entrega de la saga Xenoblade, con seis protagonistas, combate de clases y una historia extensa.',
  'juegos2-15': 'Action RPG de la saga Ys ambientado en la ciudad prisión de Balduq, con combate rápido y habilidades especiales.',
  'juegos2-16': 'Aventura de plataformas de Yoshi para Nintendo Switch 2, con escenarios artesanales y juego cooperativo.',
  'juegos2-17': 'Precuela de la saga Ys ambientada en la Torre de Darm, con combate arcade y tres personajes jugables.',

  'juegos3-00': 'Plataformas 2D de Rayman con arte dibujado a mano, niveles musicales y multijugador local.',
  'juegos3-01': 'Mundo abierto del oeste americano con Arthur Morgan, la banda de Van der Linde y un enorme mundo vivo.',
  'juegos3-02': 'Remake del survival horror clásico en Raccoon City, con Leon y Claire y motor gráfico moderno.',
  'juegos3-04': 'Remake del clásico de terror en el que Leon S. Kennedy debe rescatar a la hija del presidente.',
  'juegos3-05': 'La aventura de Leon en la aldea europea, edición para PS4 del clásico de acción y terror de Capcom.',
  'juegos3-06': 'Cuatro campañas entrelazadas con Leon, Chris, Jake y Ada, más cooperativo para dos jugadores.',
  'juegos3-07': 'Recopilación con Resident Evil HD Remaster y Resident Evil 0 HD Remaster en un solo disco.',
  'juegos3-08': 'Survival horror a bordo de un crucero a la deriva, con Jill Valentine y capítulos episódicos.',
  'juegos3-09': 'Claire Redfield y Moira Burton atrapadas en una isla, con campaña cooperativa y modo Raid.',
  'juegos3-10': 'Acción en el Japón feudal de FromSoftware, centrada en el sigilo, el parry y la dificultad exigente.',
  'juegos3-11': 'Spider-Man en Nueva York con todo el contenido descargable de La Ciudad Que Nunca Duerme incluido.',
  'juegos3-12': 'Miles Morales asume el manto de Spider-Man en Nueva York durante el invierno, con poderes bioeléctricos.',
  'juegos3-13': 'Los tres primeros juegos de Spyro remasterizados desde cero, con plataformas y coleccionables.',
  'juegos3-14': 'Aventura de acción en el universo Star Wars con el padawan Cal Kestis, combate con sable y exploración.',
  'juegos3-15': 'Combate espacial en cabina 5 contra 5, con naves rebeldes e imperiales y compatibilidad con PS VR.',
  'juegos3-16': 'JRPG de la saga Tales protagonizado por Velvet Crowe, con combate en tiempo real y una historia de venganza.',
  'juegos3-17': 'Juego de peleas 3D con el desenlace de la saga Mishima, más de 35 luchadores y modo historia.',
  'juegos3-18': 'Simulador de caza en mundo abierto con reservas enormes, fauna realista y modo cooperativo.',
  'juegos3-19': 'Juego de peleas 2D en equipos de tres, con más de 50 luchadores de la saga King of Fighters.',
  'juegos3-20': 'La historia de Joel y Ellie en un mundo devastado, en su versión remasterizada con el DLC Left Behind.',
  'juegos3-21': 'Secuela de The Last of Us protagonizada por Ellie, con combate más brutal y una narrativa dividida.',
  'juegos3-22': 'Aventura narrativa de Telltale ambientada en el universo de The Walking Dead, basada en decisiones.',
  'juegos3-23': 'Campaña de disparos con Titanes controlables y multijugador de movimiento vertical muy rápido.',
  'juegos3-24': 'Terror interactivo en una cabaña de montaña donde cada decisión define quién sobrevive.',
  'juegos3-25': 'Mundo abierto en un Londres distópico donde puedes reclutar y jugar como cualquier ciudadano.',

  'juegos4-00': 'Mundo abierto en la isla de Tsushima durante la invasión mongola, con combate a katana y sigilo.',
  'juegos4-01': 'Ghost of Tsushima con la expansión de la isla de Iki incluida y mejoras técnicas.',
  'juegos4-02': 'Action RPG de cacería de dioses con armas transformables y misiones cooperativas para cuatro jugadores.',
  'juegos4-03': 'Remasterización del cierre de la trilogía griega de Kratos, con combate brutal y jefes colosales.',
  'juegos4-05': 'Kratos y Atreus recorren los Nueve Reinos rumbo al Ragnarök, con combate y narrativa nórdica.',
  'juegos4-06': 'GTA III, Vice City y San Andreas remasterizados con controles y gráficos actualizados.',
  'juegos4-07': 'Los Santos en mundo abierto con tres protagonistas, más el acceso a GTA Online.',
  'juegos4-08': 'Metroidvania de exploración en Hallownest, con combate preciso, arte dibujado a mano y jefes memorables.',
  'juegos4-10': 'Mundo abierto de mitología griega con puzles, vuelo y combate ligero, en tono humorístico.',
  'juegos4-11': 'Aventura cooperativa obligatoria para dos jugadores, con mecánicas nuevas en cada capítulo.',
  'juegos4-13': 'Aventura LEGO con más de 150 personajes de DC, humor familiar y cooperativo a pantalla dividida.',
  'juegos4-14': 'Plataformas creativo con Sackboy y tres personajes nuevos, más un editor de niveles completo.',
  'juegos4-16': 'Aventura narrativa episódica de Telltale ambientada en el universo de Minecraft, basada en decisiones.',
  'juegos4-17': 'Caza monstruos gigantes, fabrica equipo con sus materiales y juega en cooperativo en línea.',
  'juegos4-19': 'Action RPG de PlatinumGames y Square Enix sobre androides, con combate fluido y múltiples finales.',
  'juegos4-20': 'Versión modernizada del RPG original de NieR, con combate renovado y banda sonora regrabada.',
  'juegos4-21': 'Action RPG exigente ambientado en el Japón del siglo XVI, con demonios yokai y saqueo de equipo.',
  'juegos4-22': 'Secuela de Nioh con personaje personalizable, transformaciones yokai y combate aún más profundo.',
  'juegos4-23': 'JRPG por turnos donde compaginas la vida de estudiante con las incursiones en el Metaverso.',
  'juegos4-24': 'Plataformas de acción con Ratchet y Clank, arsenal creativo y presentación tipo película animada.',

  'juegos6-00': 'Reimaginación del clásico pirata de Assassin’s Creed con Edward Kenway, navegación y abordajes.',
  'juegos6-01': 'Survival horror narrativo de Remedy con dos protagonistas, edición Deluxe con contenido adicional.',
  'juegos6-02': 'RPG por turnos basado en Dungeons & Dragons, con enorme libertad de decisión y cooperativo.',
  'juegos6-03': 'Acción y aventura de mundo abierto en el continente de Pywel, con combate variado y exploración.',
  'juegos6-04': 'Survival horror del estudio Bloober Team, ambientado en una Polonia retrofuturista.',
  'juegos6-05': 'RPG de mundo abierto en Night City, con personaje personalizable, implantes y decisiones que pesan.',
  'juegos6-06': 'Acción y terror en Los Ángeles infestado de zombis, con combate cuerpo a cuerpo y cooperativo.',
  'juegos6-07': 'Secuela de Death Stranding de Hideo Kojima, con entregas, exploración y narrativa cinematográfica.',
  'juegos6-08': 'Remake del RPG de acción de FromSoftware, exigente y con una ambientación oscura impecable.',
  'juegos6-09': 'Acción de combos de Capcom con tres personajes jugables, en su edición Special con Vergil incluido.',
  'juegos6-10': 'Precuela de DOOM con combate medieval brutal, escudo de sierra y batallas a gran escala.',
  'juegos6-11': 'Remake en HD-2D de la saga clásica de RPG de Square Enix, con combate por turnos y arte renovado.',
  'juegos6-12': 'RPG de mundo abierto de FromSoftware con historia de George R. R. Martin y exploración libre.',
  'juegos6-13': 'Spin-off cooperativo de Elden Ring para tres jugadores, con partidas de supervivencia limitadas.',
  'juegos6-14': 'Mundo abierto en la isla caribeña de Yara, con guerrilla, armas improvisadas y cooperativo.',
  'juegos6-15': 'Fútbol de EA Sports con licencias oficiales, Ultimate Team y modo carrera actualizado.',
  'juegos6-16': 'Final Fantasy VII Remake con el episodio de Yuffie incluido y mejoras técnicas para PS5.',
  'juegos6-17': 'Segunda parte del remake de Final Fantasy VII, con mundo abierto y un elenco ampliado.',
  'juegos6-18': 'RPG de acción en Valisthea protagonizado por Clive Rosfield, con combates contra Eikons.',
  'juegos6-19': 'Ghost of Tsushima con la isla de Iki, doblaje japonés labial y mejoras propias de PS5.',
  'juegos6-20': 'Kratos y Atreus rumbo al Ragnarök, en su versión para PS5 con mejor resolución y tiempos de carga.',
  'juegos6-21': 'Los Santos en su versión para PS5, con mejoras gráficas, carga rápida y acceso a GTA Online.',
  'juegos6-22': 'El Agente 47 en misiones de sigilo en escenarios abiertos, reuniendo la trilogía World of Assassination.',
  'juegos6-23': 'RPG de mundo abierto en Hogwarts durante el siglo XIX, con hechizos, criaturas y casa a elección.',
  'juegos6-24': 'Aloy explora el oeste prohibido con nuevas máquinas, escalada libre y combate táctico.',
}
